home_work
LangiviTechnology/internship-from-18-07-2021 pull request #16
Opened 2021-07-30 19:26 UTC by Sergio1222

2021-08-22 11:07 UTC, ElikaFilin requested changes

2021-08-22 11:07 UTC, ElikaFilin commented on homework.html
> +		<h1>Форма заявки на роботу в зоопарку</h1>
не відповідає дизайну

2021-08-22 11:07 UTC, ElikaFilin commented on homework.html
> +		<video src="https://www.youtube.com/watch?v=IcrbM1l_BoI&ab_channel=AviciiOfficialVEVO" controls width="500"
не працює

2021-08-23 06:16 UTC, Sergio1222 commented on homework.html
> +		<h1>Форма заявки на роботу в зоопарку</h1>
Що конкретно не відповідає?

2021-08-23 09:30 UTC, ElikaFilin commented on homework.html
> +		<h1>Форма заявки на роботу в зоопарку</h1>
в основному відступи
![зображення](https://user-images.githubusercontent.com/49747207/130424222-29597a0e-4796-40d6-b2fa-71d47a0fb6dd.png)
![зображення](https://user-images.githubusercontent.com/49747207/130424447-62a3559c-e1a2-4872-95ff-1db052b02cda.png)

2021-08-23 09:33 UTC, ElikaFilin approved these changes

2021-08-23 13:07 UTC, Sergio1222 commented on homework.html
> +		<h1>Форма заявки на роботу в зоопарку</h1>
Відступи між checkbox?

2021-09-01 20:36 UTC, merged